name: doxygen=deploy

on:
  push:
    branches: [ master ] # Make sure this is the correct branch

jobs:
  deploy-worksheet5:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history to avoid issues when pushing to gh-pages

      # Step 2: Install Doxygen
      - name: Install doxygen
        run: sudo apt-get install -y doxygen

      # Step 3: Run Doxygen on the Worksheet5 folder
      - name: Run Doxygen
        working-directory: ${{ github.workspace }}/Worksheet5
        run: doxygen

      # Step 4: Deploy to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # Specify the branch to deploy to
          folder: ${{ github.workspace }}/Worksheet5/html
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the token for authentication
